/**
 * Extended schema seed metadata (Phase 2–4).
 */
import { EXTENDED_DELIVERABLE_CODES } from './modules/extended.js'
import type { BusinessSchemaSeedSpec } from './types.js'

const EXTENDED_META: Record<string, { name: string; type: BusinessSchemaSeedSpec['type'] }> = {
  'oa-notice-list': { name: '公告列表', type: 'search_list' },
  'oa-notice-publish': { name: '公告发布', type: 'form' },
  'oa-notice-detail': { name: '公告详情', type: 'layout' },
  'oa-trip-apply': { name: '出差申请', type: 'form' },
  'oa-trip-list': { name: '出差台账', type: 'search_list' },
  'oa-trip-detail': { name: '出差详情', type: 'layout' },
  'oa-meeting-list': { name: '会议列表', type: 'search_list' },
  'oa-meeting-book': { name: '会议预约', type: 'form' },
  'oa-meeting-detail': { name: '会议详情', type: 'layout' },
  'oa-seal-apply': { name: '用印申请', type: 'form' },
  'oa-seal-list': { name: '用印台账', type: 'search_list' },
  'oa-seal-detail': { name: '用印详情', type: 'layout' },
  'oa-doc-receive': { name: '公文收文', type: 'form' },
  'oa-doc-receive-list': { name: '收文台账', type: 'search_list' },
  'oa-doc-receive-detail': { name: '收文详情', type: 'layout' },
  'oa-doc-draft': { name: '公文拟稿', type: 'form' },
  'oa-doc-draft-list': { name: '拟稿台账', type: 'search_list' },
  'oa-doc-draft-detail': { name: '拟稿详情', type: 'layout' },
  'oa-asset-apply': { name: '资产领用', type: 'form' },
  'oa-asset-list': { name: '资产领用台账', type: 'search_list' },
  'oa-asset-detail': { name: '资产领用详情', type: 'layout' },
  'oa-knowledge-entry': { name: '知识库入口', type: 'business' },
  'hr-overtime-apply': { name: '加班申请', type: 'form' },
  'hr-overtime-list': { name: '加班台账', type: 'search_list' },
  'hr-overtime-detail': { name: '加班详情', type: 'layout' },
  'hr-onboard-apply': { name: '入职办理', type: 'form' },
  'hr-onboard-list': { name: '入职台账', type: 'search_list' },
  'hr-onboard-detail': { name: '入职详情', type: 'layout' },
  'hr-resign-apply': { name: '离职办理', type: 'form' },
  'hr-resign-list': { name: '离职台账', type: 'search_list' },
  'hr-resign-detail': { name: '离职详情', type: 'layout' },
  'hr-employee-profile': { name: '员工档案', type: 'business' },
  'hr-org-chart': { name: '组织架构', type: 'business' },
  'hr-attendance-dashboard': { name: '考勤统计', type: 'chart' },
  'hr-contract-list': { name: '合同台账', type: 'search_list' },
  'hr-recruit-apply': { name: '招聘需求', type: 'form' },
  'hr-recruit-list': { name: '招聘台账', type: 'search_list' },
  'hr-recruit-detail': { name: '招聘详情', type: 'layout' },
  'hr-recruit-offer': { name: 'Offer 审批', type: 'form' },
  'fin-expense-apply': { name: '费用报销', type: 'form' },
  'fin-expense-list': { name: '报销台账', type: 'search_list' },
  'fin-expense-detail': { name: '报销详情', type: 'layout' },
  'fin-expense-stats': { name: '报销统计', type: 'chart' },
  'fin-purchase-apply': { name: '采购申请', type: 'form' },
  'fin-purchase-list': { name: '采购台账', type: 'search_list' },
  'fin-purchase-detail': { name: '采购详情', type: 'layout' },
  'fin-contract-list': { name: '合同台账', type: 'search_list' },
  'fin-contract-detail': { name: '合同详情', type: 'layout' },
  'fin-budget-edit': { name: '预算编制', type: 'form' },
  'fin-budget-list': { name: '预算编制台账', type: 'search_list' },
  'fin-budget-detail': { name: '预算详情', type: 'layout' },
  'fin-budget-dashboard': { name: '预算执行', type: 'chart' },
  'fin-payment-apply': { name: '付款申请', type: 'form' },
  'fin-payment-list': { name: '付款台账', type: 'search_list' },
  'fin-payment-detail': { name: '付款详情', type: 'layout' },
  'fin-invoice-list': { name: '发票台账', type: 'search_list' },
  'fin-invoice-register': { name: '发票登记', type: 'form' },
  'fin-invoice-detail': { name: '发票详情', type: 'layout' },
  'fin-bank-reconcile': { name: '银行对账', type: 'business' },
  'fin-monthly-close': { name: '财务月结', type: 'report' },
  'fin-ledger-balance': { name: '科目余额', type: 'report' },
  'fin-cash-plan': { name: '资金计划', type: 'form' },
  'sys-menu-manage': { name: '菜单管理', type: 'business' },
  'sys-dict-manage': { name: '字典管理', type: 'business' },
  'sys-config-manage': { name: '系统参数', type: 'business' },
  'sys-audit-log': { name: '操作审计', type: 'table' },
  'sys-login-log': { name: '登录日志', type: 'table' },
  'sys-post-manage': { name: '岗位管理', type: 'business' },
  'sys-online-users': { name: '在线用户', type: 'table' },
  'sys-tenant-manage': { name: '租户管理', type: 'business' },
  'audit-plan-list': { name: '审计计划', type: 'search_list' },
  'audit-project-list': { name: '审计项目', type: 'search_list' },
  'audit-issue-list': { name: '审计问题', type: 'search_list' },
  'audit-issue-detail': { name: '问题整改', type: 'layout' },
  'audit-report-list': { name: '审计报告', type: 'search_list' },
  'audit-plan-edit': { name: '计划编制', type: 'form' },
  'audit-project-detail': { name: '项目详情', type: 'layout' },
  'audit-working-paper': { name: '工作底稿', type: 'form' },
  'audit-rectify-track': { name: '整改跟踪', type: 'search_list' },
  'audit-compliance-check': { name: '合规检查', type: 'search_list' },
  'audit-compliance-form': { name: '合规检查表', type: 'form' },
  'audit-report-edit': { name: '报告编制', type: 'form' },
  'audit-stats-dashboard': { name: '审计统计', type: 'chart' },
  'audit-sys-log': { name: '平台操作日志', type: 'table' },
  'metrology-device-list': { name: '器具台账', type: 'search_list' },
  'metrology-device-register': { name: '器具登记', type: 'form' },
  'metrology-calibration-plan': { name: '检定计划', type: 'form' },
  'metrology-alert-dashboard': { name: '到期预警', type: 'chart' },
  'metrology-device-detail': { name: '器具详情', type: 'layout' },
  'metrology-calibration-record': { name: '检定记录', type: 'search_list' },
  'metrology-calibration-apply': { name: '检定申请', type: 'form' },
  'metrology-cert-list': { name: '证书管理', type: 'search_list' },
  'metrology-expiry-dashboard': { name: '到期预警看板', type: 'chart' },
  'metrology-stats': { name: '计量统计', type: 'chart' },
  'equipment-asset-list': { name: '装备台账', type: 'search_list' },
  'equipment-borrow-apply': { name: '装备领用', type: 'form' },
  'equipment-inventory-list': { name: '装备盘点', type: 'search_list' },
  'equip-asset-list': { name: '装备台账', type: 'search_list' },
  'equip-asset-register': { name: '装备登记', type: 'form' },
  'equip-asset-detail': { name: '装备详情', type: 'layout' },
  'equip-requisition-apply': { name: '领用申请', type: 'form' },
  'equip-requisition-list': { name: '领用台账', type: 'search_list' },
  'equip-requisition-detail': { name: '领用详情', type: 'layout' },
  'equip-return-register': { name: '归还登记', type: 'form' },
  'equip-inventory-task': { name: '盘点任务', type: 'search_list' },
  'equip-inventory-form': { name: '盘点录入', type: 'form' },
  'equip-scrap-apply': { name: '报废申请', type: 'form' },
  'equip-stats-dashboard': { name: '装备统计', type: 'chart' },
  'gov-case-apply': { name: '事项受理', type: 'form' },
  'gov-case-list': { name: '事项台账', type: 'search_list' },
  'gov-case-detail': { name: '事项详情', type: 'layout' },
  'gov-license-list': { name: '证照管理', type: 'search_list' },
  'gov-license-detail': { name: '证照详情', type: 'layout' },
  'gov-supervision-list': { name: '督查督办', type: 'search_list' },
  'gov-case-accept': { name: '事项受理', type: 'form' },
  'gov-parallel-board': { name: '并联审批看板', type: 'business' },
  'gov-license-apply': { name: '证照申请', type: 'form' },
  'gov-policy-publish': { name: '政策发布', type: 'form' },
  'gov-supervise-list': { name: '督查督办', type: 'search_list' },
  'gov-dashboard-screen': { name: '政务运行大屏', type: 'report' },
  'report-dashboard-general': { name: '综合统计', type: 'chart' },
  'report-center-home': { name: '报表中心', type: 'business' },
  'report-export-center': { name: '导出中心', type: 'business' },
  'report-exec-screen': { name: '领导驾驶舱', type: 'report' },
  'report-doc-list': { name: '报告台账', type: 'search_list' },
  'report-doc-edit': { name: '报告编制', type: 'form' },
  'report-doc-detail': { name: '报告详情', type: 'layout' },
  'report-doc-templates': { name: '报告模板', type: 'business' },
  'report-hr-summary': { name: '人事报表', type: 'report' },
  'report-fin-summary': { name: '财务报表', type: 'report' },
  'report-flow-efficiency': { name: '流程效率', type: 'chart' },
  'report-oa-summary': { name: 'OA 运营报表', type: 'report' },
  'report-audit-summary': { name: '审计报表', type: 'report' },
  'report-metrology-summary': { name: '计装报表', type: 'report' },
  'report-adhoc-query': { name: '自定义查询', type: 'search_list' },
  'report-subscription': { name: '报表订阅', type: 'form' },
  'report-doc-schedule': { name: '定期报告任务', type: 'search_list' },
  'report-doc-annual': { name: '年度报告', type: 'form' },
  'report-doc-analysis': { name: '专题分析', type: 'form' },
  'report-doc-preview': { name: '报告预览', type: 'layout' },
  'workbench-messages': { name: '消息中心', type: 'search_list' },
  'sys-micro-app-manage': { name: '微应用管理', type: 'business' },
}

export function buildExtendedSchemaSeeds(
  placeholder: (canvas: { width: number; height: number }) => Record<string, unknown>,
): BusinessSchemaSeedSpec[] {
  return EXTENDED_DELIVERABLE_CODES.map((code) => {
    const meta = EXTENDED_META[code] ?? { name: code, type: 'business' as const }
    const isForm = meta.type === 'form'
    const isChart = meta.type === 'chart' || meta.type === 'report'
    const canvas = isForm
      ? { width: 960, height: 900 }
      : isChart
        ? { width: 1920, height: 900 }
        : { width: 1440, height: 900 }
    return {
      code,
      name: meta.name,
      type: meta.type,
      json: placeholder(canvas),
    }
  })
}
